dist: bionic

jobs:
  include:
  - name: Enterprise 2.1.4.x
    env: KONG_VERSION=2.1.4.x
  - name: Enterprise 2.2.1.x
    env: KONG_VERSION=2.2.1.x
  - name: Kong CE 2.1.x
    env: KONG_VERSION=2.1.x
  - name: Kong CE 2.2.x
    env: KONG_VERSION=2.2.x
  - name: Kong CE 2.3.x
    env: KONG_VERSION=2.3.x
  - name: Nightly EE-master
    env: KONG_VERSION=nightly-ee POSTGRES=latest CASSANDRA=latest
  #- name: Nightly CE-master
  #  env: KONG_VERSION=nightly POSTGRES=latest CASSANDRA=latest

env:
  global:
  # for Enterprise images
  - BINTRAY_USERNAME=kong-automation@kong
  - BINTRAY_REPO=kong
  - secure: XRJMsixYJLZZtQMrIQCBEgI16Qf/lMh/66/MRTpPqPRg/+kmSLPWq8/ZSwCdHOCsHr3iUi3z6XLF1FABMIPRH3R4fvwJIiLLjbR3D6X+16lKA864yL0+Y5Cp8rD6oo9UjeTligGV1xqwlufzVD5tv50NXqMmxSclGTWPc3BUHZMaiFd9kKnyR/rAc6Yy1HswaaHFbjmmnygQ/OOG3VhnfgylMsKkXkTFJTQxIYqMnV3rqk0rAaSGpLyM+A7CFOEwqgJ43Ywl4f2bCyKrikolbQvWLFL9SNSFJzdz7sMpind8JWh3+xEjCZoGQvwp48CIlb4GulTiTC/e3K6tC70M1qKMfkW360NVkipXE7N++/jKpwntE0O2FBU+dIuUv2P//DU5KBo79BMbPY1xGdzc3WpvCK7i5xt3OTtGPKQ3KTQb/ZWM7kWvqmoh7Vw/qyIXRH9OUlQu0opEaa0aqCBuQXjsoEgoDX+OLUXzuq1A1qAIq5cuQaHQfEn2FFyGkWgcvkl4KoRLWateV1PwMTccQZ2ohYDpEW08kZrrPei32pBGVO+Bp9OBjJ2gfTuTRvZHsvc6wJlrohAXs4oZBkEuXJb9SpWzQuzibt0XvJ1srevZNmaQTF1kFI5867FZdrxgv6MTQ265ccDXmEH75+fyhARozSTdAAoPpBTheiGDEoY=
  # for Nightly Enterprise images
  - NIGHTLY_EE_USER=kong-automation@kong
  - secure: i1IUmr2JcrHQx8qRo7N41ltkd5tL7SGgh9CTrFEhDqFMSiWKdzuBbxQJAIV5pbyOVnMBBndJ4XJtw59zf0OgLubvDCr04yM4UdWlceIfBsWQN/AkgrvLfJWL+5UbaTTXyRvPGpJznDkSFosAy4btY2C4w8dk8Gwu15m6/s6d+hXOs+Q7+YWn4N8uQ4N03dDfoChQj5NFBFODh0jPJQbOFjNQsN7IsB8RkZjBVlFb6pGlRbcOmu2xLpIGw8bzStYTZTAM5hEvZeotQuM9a8RTOWd0OmhvFxOaLRberNPLiKFnaltfqnyfJGeZS+GLt7aSbFBfn/tkmnkFYn1sGonCkhvD07Wm0bIWoX9AU3cauY+L0t8T8OJhK+xL8lWOnXCcehfB4tJ6jQLDY0Kg76yRt8AKf/CZzukksg+MEIaon58qNXDO9XTS6ykvdsLIBfbYwjUKCgp+WfCHrJL7hshwsSrVAXDkNMfVKTug3K0VuaD9BM08X6H5xuttZ+O3vcbEXMh+2FZ5YQ3UBiF0tqYS7YvOdBMeAimr75QExkAP/dSXNb5wxcCwBCrK3gI2/3EOm96io46AQND08bqSueK8WA0lepauX500qDkBi4NjJ/wiJC/gsAz1C9/v8DFNY5g2oSoozt6tbsx6xECLOdkKlaa7kzU3zqvw65Hn2Oq3kbo=

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: QbZtpW6ihbx/K19d7u0TGk8b6+Uoydi/N8sL+D/BVYlMfFcVhZiOHGqMGK0F8ow5QTiXpqw/uXjgOID3zTSZsba9Qq+1YuqIPxkQ6Waw6VnCwnrR6Pw0/YGCDgxYQupDsfRUoMplJdAvwbpBYktJK/0Wy+45hHu8G9DbeiVfOqMLtbDo3JLhnrjBM3Yoxl0wwroQj8R47yfPBqHD9w+OaL8bWEIAHz+3AwsUSQ5H1RqmsITdmiuaRfo/WdJIVRjuRPVVDv96E34SwhjrDHlTzSC7j2RsPqAv8YHYD7Xj3lwm2OlIrfmjjM/Tk66wIMwo4ohmFsDEFXFPQKUdi+qKRAYBtFnokvFdi+paZBRhhegvWwXtlHl1mtg1irgsCdeSG/4oXufcVOXij8xjBbHBgrzpY/jne3vGGQfoBjvE3JPHhh319d7XeDzcmxQSTsRVm1VR6w3j28IyRjVt8RJsHpF15C4dg9LJMIeOhUTxHGN8Nvr/Jey2c8TJSL4RIHY8Q60iWXH54gcIXmhSuBVGwT5/Exlwk6sAFdaT8b/Ge0+iF9HgngMdd7jFJnlFNIVcGgAth79nUOuGrNBOP7+J3zK63lsXwisTn5n9I3rSWY6b0f30RR3qoU4wNKro4ZcO724e3QvmXb1pftPM3xWV+xX7IUuLqTEjn3ZwLGozS9Q=
