dist: bionic

jobs:
  include:
  - name: Kong Enterprise 1.3.0.x
    env: KONG_VERSION=1.3.0.x
  - name: Kong CE 1.5.x
    env: KONG_VERSION=1.5.x
  - name: Kong CE 2.0.x
    env: KONG_VERSION=2.0.x

env:
  global:
  - BINTRAY_USERNAME=kong-automation@kong
  - BINTRAY_REPO=kong
  - secure: XRJMsixYJLZZtQMrIQCBEgI16Qf/lMh/66/MRTpPqPRg/+kmSLPWq8/ZSwCdHOCsHr3iUi3z6XLF1FABMIPRH3R4fvwJIiLLjbR3D6X+16lKA864yL0+Y5Cp8rD6oo9UjeTligGV1xqwlufzVD5tv50NXqMmxSclGTWPc3BUHZMaiFd9kKnyR/rAc6Yy1HswaaHFbjmmnygQ/OOG3VhnfgylMsKkXkTFJTQxIYqMnV3rqk0rAaSGpLyM+A7CFOEwqgJ43Ywl4f2bCyKrikolbQvWLFL9SNSFJzdz7sMpind8JWh3+xEjCZoGQvwp48CIlb4GulTiTC/e3K6tC70M1qKMfkW360NVkipXE7N++/jKpwntE0O2FBU+dIuUv2P//DU5KBo79BMbPY1xGdzc3WpvCK7i5xt3OTtGPKQ3KTQb/ZWM7kWvqmoh7Vw/qyIXRH9OUlQu0opEaa0aqCBuQXjsoEgoDX+OLUXzuq1A1qAIq5cuQaHQfEn2FFyGkWgcvkl4KoRLWateV1PwMTccQZ2ohYDpEW08kZrrPei32pBGVO+Bp9OBjJ2gfTuTRvZHsvc6wJlrohAXs4oZBkEuXJb9SpWzQuzibt0XvJ1srevZNmaQTF1kFI5867FZdrxgv6MTQ265ccDXmEH75+fyhARozSTdAAoPpBTheiGDEoY=

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: QbZtpW6ihbx/K19d7u0TGk8b6+Uoydi/N8sL+D/BVYlMfFcVhZiOHGqMGK0F8ow5QTiXpqw/uXjgOID3zTSZsba9Qq+1YuqIPxkQ6Waw6VnCwnrR6Pw0/YGCDgxYQupDsfRUoMplJdAvwbpBYktJK/0Wy+45hHu8G9DbeiVfOqMLtbDo3JLhnrjBM3Yoxl0wwroQj8R47yfPBqHD9w+OaL8bWEIAHz+3AwsUSQ5H1RqmsITdmiuaRfo/WdJIVRjuRPVVDv96E34SwhjrDHlTzSC7j2RsPqAv8YHYD7Xj3lwm2OlIrfmjjM/Tk66wIMwo4ohmFsDEFXFPQKUdi+qKRAYBtFnokvFdi+paZBRhhegvWwXtlHl1mtg1irgsCdeSG/4oXufcVOXij8xjBbHBgrzpY/jne3vGGQfoBjvE3JPHhh319d7XeDzcmxQSTsRVm1VR6w3j28IyRjVt8RJsHpF15C4dg9LJMIeOhUTxHGN8Nvr/Jey2c8TJSL4RIHY8Q60iWXH54gcIXmhSuBVGwT5/Exlwk6sAFdaT8b/Ge0+iF9HgngMdd7jFJnlFNIVcGgAth79nUOuGrNBOP7+J3zK63lsXwisTn5n9I3rSWY6b0f30RR3qoU4wNKro4ZcO724e3QvmXb1pftPM3xWV+xX7IUuLqTEjn3ZwLGozS9Q=
