dist: bionic
jobs:
  include:
  - name: Enterprise 2.1.4.x
    env: KONG_VERSION=2.1.4.x
  - name: Enterprise 2.2.1.x
    env: KONG_VERSION=2.2.1.x
  - name: Kong CE 2.1.x
    env: KONG_VERSION=2.1.x
  - name: Kong CE 2.2.x
    env: KONG_VERSION=2.2.x
  - name: Kong CE 2.3.x
    env: KONG_VERSION=2.3.x
  - name: Nightly EE-master
    env: KONG_VERSION=nightly-ee POSTGRES=latest CASSANDRA=latest
  - name: Nightly CE-master
    env: KONG_VERSION=nightly POSTGRES=latest CASSANDRA=latest
env:
  global:
  # for Enterprise images
  - PULP_USERNAME=admin
  - secure: qLQpFz79OAmWsZuhSmOx62RIKCXT0tbPtTriTSQ00YDTzIfeU02LZ6XOuq1B4LwndaQaHHcM6K8s1vND8XBLPLuNPow6/SmWNkua3WmBxwQwNKA4oPd4Wb/M1PtI1ZCrj503WYKzdLOUPv/yez8V6IbUMuFC5iAMQdljUV+ygDWvvCB6bWdBt/cfYTP2nDp4vgkelQtaQaNuxPYFghch/mPL5pG9FavZy4sE20ckLelHDR1xuaQmvc4kuesTumbBePxzO1dRtcAZuGeAXIJBqDl7SgC0AwsfNZBXmORQGuVFthTHMWq3ZaBXOHTE/a54qz/0+YadGbGmDTQvGdBP9XA3h6eAlHWElLYVbdlNEt7zoRhP/C0dtpQus+kRzo2/GCff99CVVv0Lupve6an0AV4h46GcQ8J6J25kwvPQAhrDk8qvkcYZVspOCYU1j/2FSagj6O9E/JeKFo7JMdSllQpex43YzM1k4dnJfAf3TzSslGZVdvnEOiL2tGKHbLZkQSvR6Ax0fiF0jD9HDHcvjnFd1EBYC0pFyDM274WIte9D4LxXKp3vWwwGOoXUgxojReFNwz/xdw6JAMY+7lzO0QMRhYWs7dWn2CW5PAhC1kb+uLJwwzvWI+N70XLuEhO1ClIwH5ela0TlVwiJGutcWzcMvDg6WSr9vberwk0aXoA=
  # for Enterprise nightly images
  - DOCKER_USERNAME=kongcloudpull
  - secure: LruPuOUZuawukX4dYFrkeIQfHLkEqrXMhMgcLzNYYo/0V6vv3M7Nu2sGek8jwReNAbfXYuDM3T1U3PND5FYVJzz/FPGUdBVsCVFipjTeEKEjCrVr7gdB9yeJj91QtJum+sOoIrXj+VuRK+4VCeVhpSfB9WjnIT8NxedH7UkS1THsKA0AVIlUNGFtycS9dfCqzZivPyyVu6woUWQjyytg+90Q7KHMqtz8e3GhETNPP4bVyAjMEnc/0w1KOFJBUK0iPJ/Xbhz61z4RrnjvTG9dV75UHexI4aPOvUVZCCautKUl2TDbjO65eLeMT2+EK9T0c8wUikTjfMc/td5HfszTRs+8oOymUj7UN9LIvUShZ8PdlqiOgsIvJKrrzHkVrk3hTgw3qIsGWnj5WgP3cPKV2As7Q7FcHPmirh041bpSEI1FjfOp8zQUQlqqWLIOiFl6mYlbY6xHgvHzjiisNXhxJXfM9P5hVJneFhAmreHHwiW9dht0LmS1suwwALkmbgc892khi4qzCbtWcn7b/UzNeOmjLdSunQChvsCvv4aVnImVkvXDxmqODnJ5Ozad7Ysf28G3222fFPnVbu5zS8h/zmtSqcgHCBSP0DNx8m5ocHqh7UW7XpYjOKEMGpio/3T3GP/yogtNAdHKeJkF/iyzLYpe5tteAYgO0nLSmG+qmzk=
install:
- if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; else echo "no docker credentials to log in, watch for the rate-limit"; fi
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"
script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"
notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: QbZtpW6ihbx/K19d7u0TGk8b6+Uoydi/N8sL+D/BVYlMfFcVhZiOHGqMGK0F8ow5QTiXpqw/uXjgOID3zTSZsba9Qq+1YuqIPxkQ6Waw6VnCwnrR6Pw0/YGCDgxYQupDsfRUoMplJdAvwbpBYktJK/0Wy+45hHu8G9DbeiVfOqMLtbDo3JLhnrjBM3Yoxl0wwroQj8R47yfPBqHD9w+OaL8bWEIAHz+3AwsUSQ5H1RqmsITdmiuaRfo/WdJIVRjuRPVVDv96E34SwhjrDHlTzSC7j2RsPqAv8YHYD7Xj3lwm2OlIrfmjjM/Tk66wIMwo4ohmFsDEFXFPQKUdi+qKRAYBtFnokvFdi+paZBRhhegvWwXtlHl1mtg1irgsCdeSG/4oXufcVOXij8xjBbHBgrzpY/jne3vGGQfoBjvE3JPHhh319d7XeDzcmxQSTsRVm1VR6w3j28IyRjVt8RJsHpF15C4dg9LJMIeOhUTxHGN8Nvr/Jey2c8TJSL4RIHY8Q60iWXH54gcIXmhSuBVGwT5/Exlwk6sAFdaT8b/Ge0+iF9HgngMdd7jFJnlFNIVcGgAth79nUOuGrNBOP7+J3zK63lsXwisTn5n9I3rSWY6b0f30RR3qoU4wNKro4ZcO724e3QvmXb1pftPM3xWV+xX7IUuLqTEjn3ZwLGozS9Q=
